<?php

namespace Container7qbgEPF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sw1S33tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sw1S33t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sw1S33t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'note' => ['privates', '.errored..service_locator.sw1S33t.App\\Entity\\Note', NULL, 'Cannot autowire service ".service_locator.sw1S33t": it references class "App\\Entity\\Note" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'note' => 'App\\Entity\\Note',
        ]);
    }
}
