<?php

namespace Container7qbgEPF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H7pC9E6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h7pC9E6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h7pC9E6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'note' => ['privates', '.errored..service_locator.h7pC9E6.App\\Entity\\Note', NULL, 'Cannot autowire service ".service_locator.h7pC9E6": it references class "App\\Entity\\Note" but no such service exists.'],
        ], [
            'note' => 'App\\Entity\\Note',
        ]);
    }
}
