<?php

namespace Container7qbgEPF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FIVyFzSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FIVyFzS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FIVyFzS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\NoteController::create' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController::delete' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController::getAll' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController::showAll' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController::showOne' => ['privates', '.service_locator.h7pC9E6', 'get_ServiceLocator_H7pC9E6Service', true],
            'App\\Controller\\NoteController::update' => ['privates', '.service_locator.sw1S33t', 'get_ServiceLocator_Sw1S33tService', true],
            'App\\Controller\\TagController::create' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TagController::delete' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TagController::index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\NoteController:create' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController:delete' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController:getAll' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController:showAll' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\NoteController:showOne' => ['privates', '.service_locator.h7pC9E6', 'get_ServiceLocator_H7pC9E6Service', true],
            'App\\Controller\\NoteController:update' => ['privates', '.service_locator.sw1S33t', 'get_ServiceLocator_Sw1S33tService', true],
            'App\\Controller\\TagController:create' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TagController:delete' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TagController:index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\NoteController::create' => '?',
            'App\\Controller\\NoteController::delete' => '?',
            'App\\Controller\\NoteController::getAll' => '?',
            'App\\Controller\\NoteController::showAll' => '?',
            'App\\Controller\\NoteController::showOne' => '?',
            'App\\Controller\\NoteController::update' => '?',
            'App\\Controller\\TagController::create' => '?',
            'App\\Controller\\TagController::delete' => '?',
            'App\\Controller\\TagController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\NoteController:create' => '?',
            'App\\Controller\\NoteController:delete' => '?',
            'App\\Controller\\NoteController:getAll' => '?',
            'App\\Controller\\NoteController:showAll' => '?',
            'App\\Controller\\NoteController:showOne' => '?',
            'App\\Controller\\NoteController:update' => '?',
            'App\\Controller\\TagController:create' => '?',
            'App\\Controller\\TagController:delete' => '?',
            'App\\Controller\\TagController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
