<?php

namespace Container7qbgEPF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h7pC9E6.App\Entity\Note' shared service.
     *
     * @return \App\Entity\Note
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h7pC9E6": it references class "App\\Entity\\Note" but no such service exists.');
    }
}
